<?php

declare(strict_types=1);

namespace Matchory\Elasticsearch\Concerns;

use Closure;
use InvalidArgumentException;
use Matchory\Elasticsearch\Builder;
use Matchory\Elasticsearch\Model;

use function array_filter;
use function array_merge;
use function array_unique;
use function array_values;
use function count;
use function implode;
use function in_array;
use function is_array;
use function is_callable;
use function is_string;
use function tap;
use function value;

trait BuildsFluentQueries
{
    /**
     * Query body
     *
     * @var array
     */
    public array $body = [];

    /**
     * Ignored HTTP errors
     *
     * @var array
     */
    public array $ignores = [];

    /**
     * Query bool must
     *
     * @var array
     */
    public array $must = [];

    /**
     * Query bool must not
     *
     * @var array
     */
    public array $must_not = [];

    /**
     * Query bool should (OR conditions)
     *
     * @var array
     */
    public array $should = [];

    /**
     * Minimum number of should clauses that must match
     *
     * @var int|string|null
     */
    protected int|string|null $minimumShouldMatch = null;

    /**
     * Result aggregations
     *
     * @var array
     */
    protected array $aggregations = [];

    /**
     * Query bool filter
     *
     * @var array
     */
    protected array $filter = [];

    /**
     * Starting document offset
     * ========================
     * Starting document offset. Defaults to `0`.
     *
     * By default, you cannot page through more than 10,000 hits using the
     * `from` and `size` parameters. To page through more hits, use the
     * `search_after` parameter.
     *
     * @var int
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-search.html#search-type
     */
    protected int $from = Builder::DEFAULT_OFFSET;

    /**
     * Unique document ID
     * ==================
     * Each document has an `_id` that uniquely identifies it, which is indexed
     * so that documents can be looked up either with the GET API or the
     * `ids` query.
     * The `_id` can either be assigned at indexing time, or a unique `_id` can
     * be generated by Elasticsearch. This field is not configurable in
     * the mappings.
     *
     * The value of the `_id` field is accessible in queries such as `term`,
     * `terms`, `match`, and `query_string`.
     *
     * The `_id` field is restricted from use in aggregations, sorting, and
     * scripting. In case sorting or aggregating on the `_id` field is required,
     * it is advised to duplicate the content of the `_id` field into another
     * field that has `doc_values` enabled.
     *
     * @var string|null
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/7.10/mapping-id-field.html
     */
    protected ?string $key = null;

    /**
     * Index name
     * ==========
     * Name of the index to query. To search all data streams and indices in a
     * cluster, omit this parameter or use _all or *.
     * An index can be thought of as an optimized collection of documents and
     * each document is a collection of fields, which are the key-value pairs
     * that contain your data. By default, Elasticsearch indexes all data in
     * every field and each indexed field has a dedicated, optimized data
     * structure. For example, text fields are stored in inverted indices, and
     * numeric and geo fields are stored in BKD trees. The ability to use the
     * per-field data structures to assemble and return search results is what
     * makes Elasticsearch so fast.
     *
     * @var string|null
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-search.html
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/7.10/documents-indices.html
     */
    protected ?string $index = null;

    /**
     * Filter operators
     *
     * @var array
     */
    protected array $operators = [
        Builder::OPERATOR_EQUAL,
        Builder::OPERATOR_NOT_EQUAL,
        Builder::OPERATOR_GREATER_THAN,
        Builder::OPERATOR_GREATER_THAN_OR_EQUAL,
        Builder::OPERATOR_LOWER_THAN,
        Builder::OPERATOR_LOWER_THAN_OR_EQUAL,
        Builder::OPERATOR_LIKE,
        Builder::OPERATOR_EXISTS,
    ];

    /**
     * Scroll
     *
     * While a search request returns a single “page” of results, the scroll API
     * can be used to retrieve large numbers of results (or even all results)
     * from a single search request, in much the same way as you would use a
     * cursor on a traditional database.
     *
     * Scrolling is not intended for real time user requests, but rather for
     * processing large amounts of data, e.g. in order to reindex the contents
     * of one index into a new index with a different configuration.
     *
     * The results that are returned from a scroll request reflect the state of
     * the index at the time that the initial search request was made, like a
     * snapshot in time. Subsequent changes to documents (index, update or
     * delete) will only affect later search requests.
     *
     * In order to use scrolling, the initial search request should specify the
     * scroll parameter in the query string, which tells Elasticsearch how long
     * it should keep the “search context” alive (see Keeping the search context
     * alive), eg ?scroll=1m.
     *
     * @var string|null
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/7.10/paginate-search-results.html#scroll-search-results
     */
    protected ?string $scroll = null;

    /**
     * Scroll ID
     *
     * Identifier for the search and its search context.
     * You can use this scroll ID with the scroll API to retrieve the next batch
     * of search results for the request. See Scroll search results.
     * This parameter is only returned if the scroll query parameter is
     * specified in the request.
     *
     * @var string|null
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/7.10/paginate-search-results.html#scroll-search-results
     */
    protected ?string $scrollId = null;

    /**
     * Search Type
     *
     * There are different execution paths that can be done when executing a
     * distributed search. The distributed search operation needs to be
     * scattered to all the relevant shards and then all the results are
     * gathered back. When doing scatter/gather type execution, there are
     * several ways to do that, specifically with search engines.
     *
     * One of the questions when executing a distributed search is how much
     * results to retrieve from each shard. For example, if we have 10 shards,
     * the 1st shard might hold the most relevant results from 0 till 10, with
     * other shards results ranking below it. For this reason, when executing a
     * request, we will need to get results from 0 till 10 from all shards, sort
     * them, and then return the results if we want to ensure correct results.
     *
     * Another question, which relates to the search engine, is the fact that
     * each shard stands on its own. When a query is executed on a specific
     * shard, it does not take into account term frequencies and other search
     * engine information from the other shards. If we want to support accurate
     * ranking, we would need to first gather the term frequencies from all
     * shards to calculate global term frequencies, then execute the query on
     * each shard using these global frequencies.
     *
     * Also, because of the need to sort the results, getting back a large
     * document set, or even scrolling it, while maintaining the correct sorting
     * behavior can be a very expensive operation. For large result set
     * scrolling, it is best to sort by _doc if the order in which documents are
     * returned is not important.
     *
     * Elasticsearch is very flexible and allows to control the type of search
     * to execute on a per search request basis. The type can be configured by
     * setting the search_type parameter in the query string. The types are:
     *
     * Query Then Fetch
     * ----------------
     * Parameter value: `query_then_fetch`.
     *
     * Distributed term frequencies are calculated locally for each shard
     * running the search. We recommend this option for faster searches with
     * potentially less accurate scoring.
     *
     * This is the default setting, if you do not specify a `search_type` in
     * your request.
     *
     * Dfs, Query Then Fetch
     * ---------------------
     * Parameter value: `dfs_query_then_fetch`.
     *
     * Distributed term frequencies are calculated globally, using information
     * gathered from all shards running the search. While this option increases
     * the accuracy of scoring, it adds a round-trip to each shard, which can
     * result in slower searches.
     *
     * @var string|null
     * @psalm-var 'query_then_fetch'|'dfs_query_then_fetch'
     * @see       https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-search.html#search-type
     */
    protected ?string $searchType = null;

    /**
     * Number of hits to return
     *
     * Defines the number of hits to return. Defaults to `10`.
     *
     * By default, you cannot page through more than 10,000 hits using the
     * `from` and `size` parameters. To page through more hits, use the
     * `search_after` parameter.
     *
     * @var int
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-search.html#search-type
     */
    protected int $size = Builder::DEFAULT_LIMIT;

    /**
     * Query sort fields
     *
     * @var array
     */
    protected array $sort = [];

    /**
     * Search after values for cursor-based pagination
     *
     * @var array|null
     */
    protected ?array $searchAfterValues = null;

    /**
     * Suggest queries for autocomplete/suggestions
     *
     * @var array
     */
    protected array $suggest = [];

    /**
     * Pending sub-aggregations to be attached to parent aggregations
     *
     * @var array
     */
    protected array $pendingSubAggs = [];

    /**
     * Query returned fields list
     *
     * @var array{
     *     includes: list<string>|null,
     *     excludes: list<string>|null,
     * }|null
     */
    protected ?array $source = null;

    /**
     * Retrieves the key (document ID) the query is restricted to.
     *
     * @return string|null
     */
    public function getKey(): ?string
    {
        return $this->key;
    }

    /**
     * Retrieves all ignored fields
     *
     * @return array
     */
    public function getIgnores(): array
    {
        return $this->ignores;
    }

    /**
     * Retrieves the name of the index used for the query.
     *
     * @return string|null
     */
    public function getIndex(): ?string
    {
        return $this->index;
    }

    /**
     * Get the query scroll
     *
     * @return string|null
     */
    public function getScroll(): ?string
    {
        return $this->scroll;
    }

    public function getScrollId(): ?string
    {
        return $this->scrollId;
    }

    /**
     * Retrieves the query search type.
     *
     * @return string|null
     * @psalm-return 'query_then_fetch'|'dfs_query_then_fetch'
     * @see          https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-search-type.html
     */
    public function getSearchType(): ?string
    {
        return $this->searchType;
    }

    /**
     * Retrieves the query size (limit).
     *
     * @return int
     */
    public function getSize(): int
    {
        return $this->size;
    }

    /**
     * Retrieves the query skip (offset).
     *
     * @return int
     */
    public function getSkip(): int
    {
        return $this->from;
    }

    /**
     * Retrieves the query body.
     *
     * @return array
     */
    public function getBody(): array
    {
        $body = $this->body;

        if ($this->filter || $this->must || $this->must_not || $this->should) {
            $body['query']['bool'] = array_filter([
                'filter' => $this->filter ?: null,
                'must' => $this->must ?: null,
                'must_not' => $this->must_not ?: null,
                'should' => $this->should ?: null,
                'minimum_should_match' => $this->minimumShouldMatch,
            ]);
        }

        if ($this->sort) {
            $body['sort'] = $this->sort;
        }

        if ($this->source !== null) {
            $body['_source'] = array_filter($this->source);
        }

        if ($this->aggregations) {
            $body['aggs'] = $this->aggregations;
        }

        if ($this->suggest) {
            $body['suggest'] = $this->suggest;
        }

        if ($this->searchAfterValues !== null) {
            $body['search_after'] = $this->searchAfterValues;
        }

        return $body;
    }

    /**
     * Adds a term filter for the `_id` field.
     *
     * @param string|null $key
     *
     * @return $this
     */
    public function key(?string $key = null): static
    {
        $this->key = $key;
        $this->filter[] = [
            'term' => [
                Builder::FIELD_ID => $key,
            ],
        ];

        return $this;
    }

    /**
     * Add an aggregation to the query.
     *
     * An aggregation summarizes your data as metrics, statistics, or other
     * analytics. Aggregations help you answer questions like:
     *  - What’s the average load time for my website?
     *  - Who are my most valuable customers based on transaction volume?
     *  - What would be considered a large file on my network?
     *  - How many products are in each product category?
     *
     * Elasticsearch organizes aggregations into three categories:
     * Metric aggregations that calculate metrics, such as a sum or average,
     * from field values.
     * Bucket aggregations that group documents into buckets, also called bins,
     * based on field values, ranges, or other criteria.
     * Pipeline aggregations that take input from other aggregations instead of
     * documents or fields.
     *
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html
     *
     * @param string $name Name of the aggregation.
     * @param array|string|null $settings Aggregation configuration. If a string
     *                                    will be assumed the name of a field to
     *                                    aggregate. If an array, will be used
     *                                    as the aggregation configuration. If
     *                                    omitted, a simple terms aggregation
     *                                    will be used as a default value, using
     *                                    the aggregation name as the field.
     *
     * @return $this
     */
    public function aggregate(
        string $name,
        array|string|null $settings = null,
    ): static {
        $field = is_string($settings) ? $settings : $name;
        $settings = is_array($settings)
            ? $settings
            : [
                'terms' => [
                    'field' => $field,
                ],
            ];

        $this->aggregations[$name] = $settings;

        return $this;
    }

    /**
     * Sets the query body
     *
     * @param array $body
     *
     * @return $this
     */
    public function body(array $body = []): static
    {
        $this->body = $body;

        return $this;
    }

    /**
     * Add a condition to find documents which are some distance away from the
     * given geo point.
     *
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-geo-distance-query.html
     *
     * @param Closure|string $name A name of the field.
     * @param mixed $value A starting geo point which can be
     *                                  represented by a string 'lat,lon', an
     *                                  object like `{'lat': lat, 'lon': lon}`
     *                                  or an array like `[lon,lat]`.
     * @param string $distance A distance from the starting geo point.
     *                                  It can be for example '20km'.
     *
     * @return $this
     */
    public function distance(
        Closure|string $name,
        mixed $value,
        string $distance,
    ): static {
        if ($name instanceof Closure) {
            return tap($this, $name);
        }

        return $this->filter('geo_distance', [
            $name => $value,
            'distance' => $distance,
        ]);
    }

    public function filter(string $type, array $parameters): static
    {
        $this->filter[] = [
            $type => $parameters,
        ];

        return $this;
    }

    /**
     * Set the query where clause and retrieve the first matching document.
     *
     * @param Closure|string $name
     * @param int|string|null $operator
     * @param mixed|null $value
     *
     * @return Model|null
     * @throws InvalidArgumentException
     */
    public function firstWhere(
        Closure|string $name,
        int|string|null $operator = Builder::OPERATOR_EQUAL,
        mixed $value = null,
    ): ?Model {
        return $this
            ->where($name, $operator, $value)
            ->first();
    }

    /**
     * Adds a filter to the query
     *
     * @param Closure|string $name
     * @param int|string|null $operator
     * @param mixed|null $value
     *
     * @return $this
     * @throws InvalidArgumentException
     */
    public function where(
        Closure|string $name,
        int|string|null $operator = Builder::OPERATOR_EQUAL,
        mixed $value = null,
    ): static {
        if ($name instanceof Closure) {
            $name($this);

            return $this;
        }

        if (!$this->isOperator((string) $operator)) {
            $value = $operator;
            $operator = Builder::OPERATOR_EQUAL;
        }

        switch ((string) $operator) {
            case 'eq':
            case Builder::OPERATOR_EQUAL:
                if ($name === Builder::FIELD_ID) {
                    return $this->key((string) $value);
                }

                return $this->termFilter($name, (string) $value);

            case 'gt':
            case Builder::OPERATOR_GREATER_THAN:
                return $this->rangeFilter(
                    $name,
                    'gt',
                    $value,
                );

            case 'gte':
            case Builder::OPERATOR_GREATER_THAN_OR_EQUAL:
                return $this->rangeFilter(
                    $name,
                    'gte',
                    $value,
                );

            case 'lt':
            case Builder::OPERATOR_LOWER_THAN:
                return $this->rangeFilter(
                    $name,
                    'lt',
                    $value,
                );

            case 'lte':
            case Builder::OPERATOR_LOWER_THAN_OR_EQUAL:
                return $this->rangeFilter(
                    $name,
                    'lte',
                    $value,
                );

            case Builder::OPERATOR_LIKE:
                return $this->must('match', [
                    $name => $value,
                ]);

            case Builder::OPERATOR_EXISTS:
                return $this->whereExists($name, (bool) $value);

            default:
                throw new InvalidArgumentException(
                    "Unknown operator '{$operator}'",
                );
        }
    }

    /**
     * Add an OR condition to the query (using Elasticsearch's should clause).
     *
     * Note: When using orWhere(), at least one should clause must match.
     * You can control this with minimumShouldMatch().
     *
     * @param Closure|string $name
     * @param int|string|null $operator
     * @param mixed|null $value
     *
     * @return $this
     * @throws InvalidArgumentException
     */
    public function orWhere(
        Closure|string $name,
        int|string|null $operator = Builder::OPERATOR_EQUAL,
        mixed $value = null,
    ): static {
        if ($name instanceof Closure) {
            $name($this);

            return $this;
        }

        if (!$this->isOperator((string) $operator)) {
            $value = $operator;
            $operator = Builder::OPERATOR_EQUAL;
        }

        // Set minimum_should_match to 1 if not already set and we have should clauses
        if ($this->minimumShouldMatch === null) {
            $this->minimumShouldMatch = 1;
        }

        switch ((string) $operator) {
            case 'eq':
            case Builder::OPERATOR_EQUAL:
                if ($name === Builder::FIELD_ID) {
                    return $this->should('term', [
                        Builder::FIELD_ID => $value,
                    ]);
                }

                return $this->should('term', [
                    $name => $value,
                ]);

            case 'gt':
            case Builder::OPERATOR_GREATER_THAN:
                return $this->should('range', [
                    $name => ['gt' => $value],
                ]);

            case 'gte':
            case Builder::OPERATOR_GREATER_THAN_OR_EQUAL:
                return $this->should('range', [
                    $name => ['gte' => $value],
                ]);

            case 'lt':
            case Builder::OPERATOR_LOWER_THAN:
                return $this->should('range', [
                    $name => ['lt' => $value],
                ]);

            case 'lte':
            case Builder::OPERATOR_LOWER_THAN_OR_EQUAL:
                return $this->should('range', [
                    $name => ['lte' => $value],
                ]);

            case Builder::OPERATOR_LIKE:
                return $this->should('match', [
                    $name => $value,
                ]);

            case Builder::OPERATOR_EXISTS:
                if ((bool) $value) {
                    return $this->should('exists', [
                        'field' => $name,
                    ]);
                }

                // For NOT EXISTS in OR context, we need a bool query with must_not
                return $this->should('bool', [
                    'must_not' => [
                        ['exists' => ['field' => $name]],
                    ],
                ]);

            default:
                throw new InvalidArgumentException(
                    "Unknown operator '{$operator}'",
                );
        }
    }

    /**
     * Adds a should condition to the query (OR logic).
     *
     * @param string $type Query type
     * @param array $parameters Parameters to the query
     *
     * @return $this
     */
    public function should(string $type, array $parameters): static
    {
        $this->should[] = [
            $type => $parameters,
        ];

        return $this;
    }

    /**
     * Set the minimum number of should clauses that must match.
     *
     * @param int|string $minimum Number or percentage (e.g., "75%")
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html#bool-min-should-match
     */
    public function minimumShouldMatch(int|string $minimum): static
    {
        $this->minimumShouldMatch = $minimum;

        return $this;
    }

    /**
     * check if it's a valid operator
     *
     * @param string $string
     *
     * @return bool
     */
    protected function isOperator(string $string): bool
    {
        return in_array(
            $string,
            $this->operators,
            true,
        );
    }

    /**
     * Shorthand to add a "term" filter.
     *
     * @param string $field Name of the field to add a filter for
     * @param mixed $value Filter value. Either a string value,
     *                                     an array of Elasticsearch parameters,
     *                                     or a callable that returns either of
     *                                     the previous.
     *
     * @return $this
     */
    public function termFilter(string $field, mixed $value): static
    {
        return $this->filter('term', [
            $field => value($value, $this, $field),
        ]);
    }

    /**
     * Shorthand to add a "range" filter.
     *
     * @param string $field Name of the field to add a filter
     *                                             for
     * @param callable|array|string $operator Range comparison operator as a
     *                                             string, an array of custom range
     *                                             comparison parameters or a
     *                                             callable that returns either of
     *                                             the previous.
     * @param callable|array|string|null $value Filter value. Either a string
     *                                             value, an array of Elasticsearch
     *                                             parameters, or a callable that
     *                                             returns either of the previous.
     *                                             Only used if a string operator has
     *                                             been passed as the second argument
     *
     * @return $this
     * @example $query->rangeFilter('year', ['gte' => '2006'])
     * @example $query->rangeFilter('year', ['gte' => '2006', 'lt' => '2021'])
     * @example $query->rangeFilter('year', fn($q, $field) => 'lt', '2021')
     * @example $query->rangeFilter('year', fn($q, $field) => ['lt' => '2021'])
     *
     * @example $query->rangeFilter('year', 'gt', '2006')
     */
    public function rangeFilter(
        string $field,
        mixed $operator,
        mixed $value = null,
    ): static {
        $operator = value($operator, $this, $field);

        if (is_string($operator) && $value) {
            return $this->filter('range', [
                $field => [
                    $operator => value($value, $this, $field),
                ],
            ]);
        }

        return $this->filter('range', [
            [
                $field => $operator,
            ],
        ]);
    }

    /**
     * Adds a must condition to the query.
     *
     * @param string $type Query type
     * @param array $parameters Parameters to the query
     *
     * @return $this
     */
    public function must(string $type, array $parameters): static
    {
        $this->must[] = [
            $type => $parameters,
        ];

        return $this;
    }

    /**
     * Set the query where exists clause
     *
     * @param string $name
     * @param bool $exists
     *
     * @return $this
     */
    public function whereExists(string $name, bool $exists = true): static
    {
        if ($exists) {
            return $this->must('exists', [
                'field' => $name,
            ]);
        }

        return $this->mustNot('exists', [
            'field' => $name,
        ]);
    }

    /**
     * Adds a must_not condition to the query.
     *
     * @param string $type Query type
     * @param array $parameters Parameters to the query
     *
     * @return $this
     */
    public function mustNot(string $type, array $parameters): static
    {
        $this->must_not[] = [
            $type => $parameters,
        ];

        return $this;
    }

    /**
     * Set the collapse field
     *
     * @param string $field
     *
     * @return $this
     */
    public function groupBy(string $field): static
    {
        $this->body['collapse'] = [
            'field' => $field,
        ];

        return $this;
    }

    /**
     * Get highlight result
     *
     * @param mixed ...$args
     *
     * @return $this
     */
    public function highlight(...$args): static
    {
        $fields = $this->flattenArgs($args);
        $new_fields = [];

        foreach ($fields as $field) {
            $new_fields[$field] = (object) [];
        }

        $this->body['highlight'] = [
            'fields' => $new_fields,
        ];

        return $this;
    }

    /**
     * @template TKey of array-key
     * @template TValue
     *
     * @param array<TKey, TValue> $args
     *
     * @return list<TValue>
     */
    private function flattenArgs(array $args): array
    {
        $flattened = [];

        foreach ($args as $arg) {
            if (is_array($arg)) {
                /** @noinspection SlowArrayOperationsInLoopInspection */
                $flattened = array_merge($flattened, $arg);
            } else {
                $flattened[] = $arg;
            }
        }

        return $flattened;
    }

    /**
     * Avoids throwing an error on unsuccessful responses from the Elasticsearch
     * server, as returned by the Elasticsearch client.
     *
     * @param mixed ...$args
     *
     * @return $this
     */
    public function ignore(...$args): static
    {
        $this->ignores = array_merge(
            $this->ignores,
            $this->flattenArgs($args),
        );

        $this->ignores = array_unique($this->ignores);

        return $this;
    }

    /**
     * Sets the name of the index to use for the query.
     *
     * @param string|null $index
     *
     * @return $this
     */
    public function index(?string $index = null): static
    {
        $this->index = $index;

        return $this;
    }

    /**
     * Shorthand to add a "match" filter.
     *
     * @param string $field Name of the field to add a filter for
     * @param mixed $value Filter value. Either a string value,
     *                                     an array of Elasticsearch parameters,
     *                                     or a callable that returns either of
     *                                     the previous.
     *
     * @return $this
     */
    public function matchFilter(
        string $field,
        mixed $value,
    ): static {
        return $this->filter('match', [
            $field => value($value, $this, $field),
        ]);
    }

    /**
     * @param string $path
     *
     * @return $this
     */
    public function nested(string $path): static
    {
        $this->body = [
            'query' => [
                'nested' => [
                    'path' => $path,
                ],
            ],
        ];

        return $this;
    }

    /**
     * Set the sorting field
     *
     * @param int|string $field
     * @param string $direction
     *
     * @return $this
     */
    public function orderBy(int|string $field, string $direction = 'asc'): static
    {
        $this->sort[] = [$field => $direction];

        return $this;
    }

    /**
     * Shorthand to add a "prefix" filter.
     *
     * @param string $field Name of the field to add a filter for
     * @param mixed $value Filter value. Either a string value,
     *                                     an array of Elasticsearch parameters,
     *                                     or a callable that returns either of
     *                                     the previous.
     *
     * @return $this
     */
    public function prefixFilter(string $field, mixed $value): static
    {
        return $this->filter('prefix', [
            $field => value($value, $this, $field),
        ]);
    }

    /**
     * Shorthand to add a "regexp" filter.
     *
     * @param string $field Name of the field to add a filter for
     * @param mixed $value Filter value. Either a string value, an array of
     *                     Elasticsearch parameters, or a callable that returns
     *                     either of the previous.
     * @param int|null $flags Enables optional operators for the regular
     *                        expression.
     * @param bool|null $caseSensitivity Allows case-insensitive matching of the
     *                                   regular expression value with the
     *                                   indexed field values when set to true.
     *                                   Default is false which means the case
     *                                   sensitivity of matching depends on the
     *                                   underlying field's mapping.
     * @param int|null $maxDeterminizedStates Maximum number of automaton states
     *                                        required for the query. Default is
     *                                        10000. Elasticsearch uses Apache
     *                                        Lucene internally to parse regular
     *                                        expressions. Lucene converts each
     *                                        regular expression to a finite
     *                                        automaton containing a number of
     *                                        determinized states. You can use
     *                                        this parameter to prevent that
     *                                        conversion from unintentionally
     *                                        consuming too many resources.
     *                                        You may need to increase this
     *                                        limit to run complex regular
     *                                        expressions.
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/regexp-syntax.html#regexp-optional-operators
     */
    public function regexpFilter(
        string $field,
        mixed $value,
        ?int $flags = null,
        ?bool $caseSensitivity = null,
        ?int $maxDeterminizedStates = null,
    ): static {
        $value = value($value, $this, $field);

        if (is_array($value) || (
            $flags === null
                && $caseSensitivity === null
                && $maxDeterminizedStates === null
        )) {
            return $this->filter('regexp', [
                $field => $value,
            ]);
        }

        $parameters = [
            'value' => $value,
        ];

        $stringFlags = $this->resolveRegexpFlags($flags ?? 0);

        if ($stringFlags) {
            $parameters['flags'] = $stringFlags;
        }

        if ($caseSensitivity !== null) {
            $parameters['case_insensitive'] = $caseSensitivity;
        }

        if ($maxDeterminizedStates !== null) {
            $parameters['max_determinized_states'] = $maxDeterminizedStates;
        }

        return $this->filter('regexp', [
            $field => $parameters,
        ]);
    }

    private function resolveRegexpFlags(int $flags): ?string
    {
        $stringFlags = [];

        if ($flags & Builder::REGEXP_FLAG_ALL) {
            $stringFlags[] = 'ALL';
        }

        if ($flags & Builder::REGEXP_FLAG_COMPLEMENT) {
            $stringFlags[] = 'COMPLEMENT';
        }

        if ($flags & Builder::REGEXP_FLAG_INTERVAL) {
            $stringFlags[] = 'INTERVAL';
        }

        if ($flags & Builder::REGEXP_FLAG_INTERSECTION) {
            $stringFlags[] = 'INTERSECTION';
        }

        if ($flags & Builder::REGEXP_FLAG_ANYSTRING) {
            $stringFlags[] = 'ANYSTRING';
        }

        if (empty($stringFlags)) {
            return null;
        }

        return implode('|', $stringFlags);
    }

    /**
     * Enables the scroll API. The argument may be used to set the duration to
     * keep the scroll ID alive for. Defaults to 5 minutes.
     *
     * @param string $keepAlive
     *
     * @return $this
     */
    public function scroll(string $keepAlive = '5m'): static
    {
        $this->scroll = $keepAlive;

        return $this;
    }

    /**
     * Sets the query scroll ID.
     *
     * @param string|null $scroll
     *
     * @return $this
     */
    public function scrollId(?string $scroll): static
    {
        $this->scrollId = $scroll;

        return $this;
    }

    /**
     * Search the entire document fields
     *
     * @param string|null $queryString
     * @param callable|array|null $settings
     * @param int|null $boost
     *
     * @return $this
     */
    public function search(
        ?string $queryString = null,
        callable|array|null $settings = null,
        ?int $boost = null,
    ): static {
        if (!$queryString) {
            return $this;
        }

        $params = ['query' => $queryString];
        $fields = [];

        if (is_callable($settings)) {
            $config = new class {
                public ?int $boost = null;

                public array $fields = [];

                public function boost(int $boost): self
                {
                    $this->boost = $boost;

                    return $this;
                }

                public function fields(array $fields): self
                {
                    foreach ($fields as $field => $weight) {
                        $this->fields[] = $weight > 1 ? "{$field}^{$weight}" : $field;
                    }

                    return $this;
                }
            };

            $settings($config);
            $boost = $config->boost ?? $boost;
            $fields = $config->fields;
        }

        if ($boost !== null && $boost > 1) {
            $params['boost'] = $boost;
        }

        if ($fields) {
            $params['fields'] = $fields;
        }

        $this->must[] = ['query_string' => $params];

        return $this;
    }

    /**
     * Sets the query search type.
     *
     * @param string $type
     *
     * @psalm-param 'query_then_fetch'|'dfs_query_then_fetch' $type
     *
     * @return $this
     * @throws InvalidArgumentException
     * @see         https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-search-type.html
     */
    public function searchType(string $type): static
    {
        $validTypes = ['query_then_fetch', 'dfs_query_then_fetch'];

        if (!in_array($type, $validTypes, true)) {
            throw new InvalidArgumentException(
                "Invalid search type '{$type}'. Valid types are: " . implode(', ', $validTypes),
            );
        }

        $this->searchType = $type;

        return $this;
    }

    /**
     * Set the query fields to return
     *
     * @param mixed ...$args
     *
     * @return $this
     */
    public function select(...$args): static
    {
        /** @var list<string> $fields */
        $fields = $this->flattenArgs($args);

        $this->source[Builder::SOURCE_INCLUDES] = array_values(
            array_unique(
                array_merge(
                    $this->source[Builder::SOURCE_INCLUDES] ?? [],
                    $fields,
                ),
            ),
        );

        $this->source[Builder::SOURCE_EXCLUDES] = array_values(
            array_filter(
                $this->source[Builder::SOURCE_EXCLUDES] ?? [],
                fn($field) => !in_array(
                    $field,
                    $this->source[Builder::SOURCE_INCLUDES] ?? [],
                ),
            ),
        );

        return $this;
    }

    /**
     * Set the query offset
     *
     * @param int $from
     *
     * @return $this
     */
    public function skip(int $from = 0): static
    {
        $this->from = $from;

        return $this;
    }

    /**
     * Sets the number of hits to return from the result.
     *
     * @param int $size
     *
     * @return $this
     */
    public function take(int $size = Builder::DEFAULT_LIMIT): static
    {
        $this->size = $size;

        return $this;
    }

    /**
     * Sets the number of hits to return from the result.
     *
     * Alias for take() to match Eloquent's naming convention.
     *
     * @param int $limit
     *
     * @return $this
     */
    public function limit(int $limit = Builder::DEFAULT_LIMIT): static
    {
        return $this->take($limit);
    }

    /**
     * Set the starting document offset (alias for skip)
     *
     * @param int $from
     *
     * @return $this
     *
     * @deprecated Use skip() instead for Eloquent compatibility
     */
    public function from(int $from = 0): static
    {
        trigger_error(
            'from() is deprecated, use skip() instead',
            E_USER_DEPRECATED,
        );

        return $this->skip($from);
    }

    /**
     * Set the number of hits to return (alias for take)
     *
     * @param int $size
     *
     * @return $this
     *
     * @deprecated Use take() or limit() instead for Eloquent compatibility
     */
    public function size(int $size = Builder::DEFAULT_LIMIT): static
    {
        trigger_error(
            'size() is deprecated, use take() or limit() instead',
            E_USER_DEPRECATED,
        );

        return $this->take($size);
    }

    /**
     * Exclude specific fields from the results.
     *
     * This is the inverse of select() - it specifies which fields should NOT
     * be returned in the document source.
     *
     * @param mixed ...$args Field names to exclude
     *
     * @return $this
     */
    public function except(...$args): static
    {
        /** @var list<string> $fields */
        $fields = $this->flattenArgs($args);

        $this->source[Builder::SOURCE_EXCLUDES] = array_values(
            array_unique(
                array_merge(
                    $this->source[Builder::SOURCE_EXCLUDES] ?? [],
                    $fields,
                ),
            ),
        );

        $this->source[Builder::SOURCE_INCLUDES] = array_values(
            array_filter(
                $this->source[Builder::SOURCE_INCLUDES] ?? [],
                fn($field) => !in_array(
                    $field,
                    $this->source[Builder::SOURCE_EXCLUDES] ?? [],
                ),
            ),
        );

        return $this;
    }

    /**
     * Set the ignored fields to not be returned
     *
     * @param mixed ...$args
     *
     * @return $this
     *
     * @deprecated Use except() instead for better clarity
     */
    public function unselect(...$args): static
    {
        trigger_error(
            'unselect() is deprecated, use except() instead',
            E_USER_DEPRECATED,
        );

        return $this->except(...$args);
    }

    /**
     * Set the query where between clause
     *
     * @param string $name
     * @param mixed $firstValue
     * @param mixed|null $lastValue
     *
     * @return $this
     */
    public function whereBetween(
        string $name,
        mixed $firstValue,
        mixed $lastValue = null,
    ): static {
        if (is_array($firstValue) && count($firstValue) === 2) {
            [$firstValue, $lastValue] = $firstValue;
        }

        return $this->filter('range', [
            $name => [
                'gte' => $firstValue,
                'lte' => $lastValue,
            ],
        ]);
    }

    /**
     * Set the query where in clause
     *
     * @param Closure|string $name
     * @param mixed|array $value
     *
     * @return $this
     */
    public function whereIn(Closure|string $name, mixed $value = []): static
    {
        if ($name instanceof Closure) {
            return tap($this, $name);
        }

        return $this->termsFilter($name, $value);
    }

    /**
     * Shorthand to add a "terms" filter.
     *
     * @param string $field Name of the field to add a filter for
     * @param mixed $value Filter value. Either a string value, an
     *                              array of Elasticsearch parameters, or a
     *                              callable that returns either of the previous
     * @param int|float|null $boost Floating point number used to decrease or
     *                              increase the relevance scores of a query.
     *                              Defaults to 1.0. You can use the boost
     *                              parameter to adjust relevance scores for
     *                              searches containing two or more queries.
     *                              Boost values are relative to the default
     *                              value of 1.0. A boost value between 0 and
     *                              1.0 decreases the relevance score. A value
     *                              greater than 1.0 increases the relevance
     *                              score.
     *
     * @return $this
     */
    public function termsFilter(
        string $field,
        mixed $value,
        int|float|null $boost = null,
    ): static {
        $value = value($value, $this, $field);

        if ($boost === null) {
            return $this->filter('terms', [
                $field => $value,
            ]);
        }

        return $this->filter('terms', [
            $field => $value,
            'boost' => $boost,
        ]);
    }

    /**
     * Set the query inverse where clause
     *
     * @param Closure|string $name
     * @param string $operator
     * @param null $value
     *
     * @return $this
     */
    public function whereNot(
        Closure|string $name,
        string $operator = Builder::OPERATOR_EQUAL,
        $value = null,
    ): static {
        if ($name instanceof Closure) {
            return tap($this, $name);
        }

        if (!$this->isOperator($operator)) {
            $value = $operator;
            $operator = Builder::OPERATOR_EQUAL;
        }

        switch ($operator) {
            case 'eq':
            case Builder::OPERATOR_EQUAL:
                return $this->mustNot('term', [
                    $name => $value,
                ]);

            case 'gt':
            case Builder::OPERATOR_GREATER_THAN:
                return $this->mustNot('range', [
                    $name => ['gt' => $value],
                ]);

            case 'gte':
            case Builder::OPERATOR_GREATER_THAN_OR_EQUAL:
                return $this->mustNot('range', [
                    $name => ['gte' => $value],
                ]);

            case 'lt':
            case Builder::OPERATOR_LOWER_THAN:
                return $this->mustNot('range', [
                    $name => ['lt' => $value],
                ]);

            case 'lte':
            case Builder::OPERATOR_LOWER_THAN_OR_EQUAL:
                return $this->mustNot('range', [
                    $name => ['lte' => $value],
                ]);

            case Builder::OPERATOR_LIKE:
                return $this->mustNot('match', [
                    $name => $value,
                ]);

            case Builder::OPERATOR_EXISTS:
                $this->whereExists($name, !$value);
        }

        return $this;
    }

    /**
     * Set the query where not between clause
     *
     * @param string $name
     * @param mixed $firstValue
     * @param mixed|null $lastValue
     *
     * @return $this
     */
    public function whereNotBetween(
        string $name,
        mixed $firstValue,
        mixed $lastValue = null,
    ): static {
        if (is_array($firstValue) && count($firstValue) === 2) {
            [$firstValue, $lastValue] = $firstValue;
        }

        return $this->mustNot('range', [
            $name => [
                'gte' => $firstValue,
                'lte' => $lastValue,
            ],
        ]);
    }

    /**
     * Set the query where not in clause
     *
     * @param Closure|string $name
     * @param mixed|array $value
     *
     * @return $this
     */
    public function whereNotIn(Closure|string $name, mixed $value = []): static
    {
        if ($name instanceof Closure) {
            return tap($this, $name);
        }

        return $this->mustNot('terms', [
            $name => $value,
        ]);
    }

    /**
     * Shorthand to add a "wildcard" filter.
     *
     * @param string $field Name of the field to add a filter for
     * @param mixed $value Filter value. Either a string value,
     *                                     an array of Elasticsearch parameters,
     *                                     or a callable that returns either of
     *                                     the previous.
     *
     * @return $this
     */
    public function wildcardFilter(
        string $field,
        mixed $value,
    ): static {
        return $this->filter('wildcard', [
            $field => value($value, $this, $field),
        ]);
    }

    /**
     * Enable query profiling.
     *
     * The Profile API provides detailed timing information about the execution
     * of individual components in a search request. It gives the user insight
     * into how search requests are executed at a low level so that the user
     * can understand why certain requests are slow, and take steps to
     * improve them.
     *
     * Note: The Profile API adds significant overhead to search execution and
     * can significantly slow down search requests. It should only be used for
     * debugging and optimization purposes, never in production.
     *
     * @param bool $enable Whether to enable profiling (default: true)
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-profile.html
     */
    public function profile(bool $enable = true): static
    {
        $this->body['profile'] = $enable;

        return $this;
    }

    /**
     * Add a fuzzy query for typo-tolerant search.
     *
     * Returns documents that contain terms similar to the search term, as
     * measured by a Levenshtein edit distance.
     *
     * @param string $field Field to search
     * @param mixed $value Value to search for (can be a callable)
     * @param string $fuzziness Maximum edit distance (AUTO, 0, 1, 2)
     * @param int|null $prefixLength Number of beginning characters left unchanged
     * @param int|null $maxExpansions Maximum number of terms to match
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-fuzzy-query.html
     */
    public function fuzzy(
        string $field,
        mixed $value,
        string $fuzziness = 'AUTO',
        ?int $prefixLength = null,
        ?int $maxExpansions = null,
    ): static {
        $params = [
            'value' => value($value, $this, $field),
            'fuzziness' => $fuzziness,
        ];

        if ($prefixLength !== null) {
            $params['prefix_length'] = $prefixLength;
        }

        if ($maxExpansions !== null) {
            $params['max_expansions'] = $maxExpansions;
        }

        return $this->filter('fuzzy', [$field => $params]);
    }

    /**
     * Add a match phrase query for exact phrase matching.
     *
     * Analyzes the text and creates a phrase query out of the analyzed text.
     *
     * @param string $field Field to search
     * @param mixed $value Phrase to search for (can be a callable)
     * @param int|null $slop Maximum number of positions allowed between matching tokens
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query-phrase.html
     */
    public function matchPhrase(
        string $field,
        mixed $value,
        ?int $slop = null,
    ): static {
        $params = ['query' => value($value, $this, $field)];

        if ($slop !== null) {
            $params['slop'] = $slop;
        }

        return $this->must('match_phrase', [$field => $params]);
    }

    /**
     * Add a match phrase prefix query for autocomplete-style searches.
     *
     * Returns documents that contain the words of a provided text, in the
     * same order as provided. The last term of the provided text is treated
     * as a prefix, matching any words that begin with that term.
     *
     * @param string $field Field to search
     * @param mixed $value Phrase prefix to search for (can be a callable)
     * @param int|null $maxExpansions Maximum number of terms to match for the prefix
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query-phrase-prefix.html
     */
    public function matchPhrasePrefix(
        string $field,
        mixed $value,
        ?int $maxExpansions = null,
    ): static {
        $params = ['query' => value($value, $this, $field)];

        if ($maxExpansions !== null) {
            $params['max_expansions'] = $maxExpansions;
        }

        return $this->must('match_phrase_prefix', [$field => $params]);
    }

    /**
     * Set the minimum score for returned documents.
     *
     * Excludes documents which have a _score less than the minimum specified.
     *
     * @param float $score Minimum score threshold
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html
     */
    public function minScore(float $score): static
    {
        $this->body['min_score'] = $score;

        return $this;
    }

    /**
     * Set the search_after values for cursor-based deep pagination.
     *
     * You can use the search_after parameter to retrieve the next page of
     * hits using a set of sort values from the previous page. Using
     * search_after requires multiple search requests with the same query
     * and sort values.
     *
     * @param array $sortValues Sort values from the last document of the previous page
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after
     */
    public function searchAfter(array $sortValues): static
    {
        $this->searchAfterValues = $sortValues;

        return $this;
    }

    /**
     * Control how the total number of hits should be tracked.
     *
     * When set to true (default), the search response will always track the
     * number of hits that match the query accurately. When set to false,
     * the search returns an approximate count. Setting to an integer
     * enables counting accurately up to the specified limit.
     *
     * @param bool|int $track Track total hits flag or limit
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-your-data.html#track-total-hits
     */
    public function trackTotalHits(bool|int $track = true): static
    {
        $this->body['track_total_hits'] = $track;

        return $this;
    }

    /**
     * Add a completion suggester for autocomplete functionality.
     *
     * The completion suggester provides auto-complete/search-as-you-type
     * functionality. This is a navigational feature to guide users to
     * relevant results as they are typing, improving search precision.
     *
     * @param string $name Name for this suggester
     * @param string $text Input text for suggestions
     * @param string $field Field with completion mapping
     * @param int $size Maximum number of suggestions
     * @param array $contexts Context filters for category-aware suggestions
     * @param bool $skipDuplicates Whether to skip duplicate suggestions
     * @param string|null $fuzzy Fuzziness for typo tolerance (AUTO, 0, 1, 2)
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html#completion-suggester
     */
    public function suggest(
        string $name,
        string $text,
        string $field,
        int $size = 5,
        array $contexts = [],
        bool $skipDuplicates = false,
        ?string $fuzzy = null,
    ): static {
        $completion = [
            'field' => $field,
            'size' => $size,
            'skip_duplicates' => $skipDuplicates,
        ];

        if (!empty($contexts)) {
            $completion['contexts'] = $contexts;
        }

        if ($fuzzy !== null) {
            $completion['fuzzy'] = ['fuzziness' => $fuzzy];
        }

        $this->suggest[$name] = [
            'prefix' => $text,
            'completion' => $completion,
        ];

        return $this;
    }

    /**
     * Add a term suggester for spelling corrections.
     *
     * The term suggester suggests terms based on edit distance. The provided
     * suggest text is analyzed before terms are suggested.
     *
     * @param string $name Name for this suggester
     * @param string $text Input text for suggestions
     * @param string $field Field to get suggestions from
     * @param int $size Maximum number of suggestions per token
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html#term-suggester
     */
    public function suggestTerm(
        string $name,
        string $text,
        string $field,
        int $size = 5,
    ): static {
        $this->suggest[$name] = [
            'text' => $text,
            'term' => [
                'field' => $field,
                'size' => $size,
            ],
        ];

        return $this;
    }

    /**
     * Add a terms aggregation.
     *
     * @param string $name Aggregation name
     * @param string $field Field to aggregate on
     * @param int $size Maximum number of buckets to return
     * @param array $options Additional options (e.g., order, min_doc_count)
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html
     */
    public function termsAgg(
        string $name,
        string $field,
        int $size = 10,
        array $options = [],
    ): static {
        return $this->addBucketAgg($name, 'terms', array_merge(
            ['field' => $field, 'size' => $size],
            $options,
        ));
    }

    /**
     * Add an avg (average) metric aggregation.
     *
     * @param string $name Aggregation name
     * @param string $field Field to compute average on
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-avg-aggregation.html
     */
    public function avgAgg(string $name, string $field): static
    {
        return $this->addMetricAgg($name, 'avg', $field);
    }

    /**
     * Add a sum metric aggregation.
     *
     * @param string $name Aggregation name
     * @param string $field Field to compute sum on
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-sum-aggregation.html
     */
    public function sumAgg(string $name, string $field): static
    {
        return $this->addMetricAgg($name, 'sum', $field);
    }

    /**
     * Add a min metric aggregation.
     *
     * @param string $name Aggregation name
     * @param string $field Field to find minimum on
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-min-aggregation.html
     */
    public function minAgg(string $name, string $field): static
    {
        return $this->addMetricAgg($name, 'min', $field);
    }

    /**
     * Add a max metric aggregation.
     *
     * @param string $name Aggregation name
     * @param string $field Field to find maximum on
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-max-aggregation.html
     */
    public function maxAgg(string $name, string $field): static
    {
        return $this->addMetricAgg($name, 'max', $field);
    }

    /**
     * Add a cardinality metric aggregation (approximate distinct count).
     *
     * @param string $name Aggregation name
     * @param string $field Field to count distinct values on
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html
     */
    public function cardinalityAgg(string $name, string $field): static
    {
        return $this->addMetricAgg($name, 'cardinality', $field);
    }

    /**
     * Add a value_count metric aggregation.
     *
     * @param string $name Aggregation name
     * @param string $field Field to count values on
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-valuecount-aggregation.html
     */
    public function valueCountAgg(string $name, string $field): static
    {
        return $this->addMetricAgg($name, 'value_count', $field);
    }

    /**
     * Add a stats metric aggregation (min, max, sum, count, avg).
     *
     * @param string $name Aggregation name
     * @param string $field Field to compute stats on
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-stats-aggregation.html
     */
    public function statsAgg(string $name, string $field): static
    {
        return $this->addMetricAgg($name, 'stats', $field);
    }

    /**
     * Add a date histogram bucket aggregation.
     *
     * @param string $name Aggregation name
     * @param string $field Date field to aggregate on
     * @param string $interval Calendar interval (minute, hour, day, week, month, quarter, year)
     * @param string|null $format Output date format
     * @param array $options Additional options (e.g., time_zone, offset)
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html
     */
    public function dateHistogramAgg(
        string $name,
        string $field,
        string $interval,
        ?string $format = null,
        array $options = [],
    ): static {
        $config = array_merge([
            'field' => $field,
            'calendar_interval' => $interval,
        ], $options);

        if ($format !== null) {
            $config['format'] = $format;
        }

        return $this->addBucketAgg($name, 'date_histogram', $config);
    }

    /**
     * Add a histogram bucket aggregation.
     *
     * @param string $name Aggregation name
     * @param string $field Numeric field to aggregate on
     * @param int|float $interval Bucket interval width
     * @param array $options Additional options (e.g., min_doc_count, extended_bounds)
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-histogram-aggregation.html
     */
    public function histogramAgg(
        string $name,
        string $field,
        int|float $interval,
        array $options = [],
    ): static {
        return $this->addBucketAgg($name, 'histogram', array_merge([
            'field' => $field,
            'interval' => $interval,
        ], $options));
    }

    /**
     * Add a range bucket aggregation.
     *
     * @param string $name Aggregation name
     * @param string $field Field to apply ranges on
     * @param array $ranges Array of range definitions with 'from' and/or 'to' keys
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-range-aggregation.html
     */
    public function rangeAgg(
        string $name,
        string $field,
        array $ranges,
    ): static {
        return $this->addBucketAgg($name, 'range', [
            'field' => $field,
            'ranges' => $ranges,
        ]);
    }

    /**
     * Add a filter bucket aggregation.
     *
     * @param string $name Aggregation name
     * @param array $filter Filter query definition
     *
     * @return $this
     * @see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-filter-aggregation.html
     */
    public function filterAgg(string $name, array $filter): static
    {
        return $this->addBucketAgg($name, 'filter', $filter);
    }

    /**
     * Add a sub-aggregation to a parent aggregation.
     *
     * Call this method before defining the parent aggregation.
     *
     * @param string $parentName Parent aggregation name
     * @param string $childName Sub-aggregation name
     * @param array $config Sub-aggregation configuration
     *
     * @return $this
     */
    public function subAgg(string $parentName, string $childName, array $config): static
    {
        if (!isset($this->pendingSubAggs[$parentName])) {
            $this->pendingSubAggs[$parentName] = ['aggs' => []];
        }

        $this->pendingSubAggs[$parentName]['aggs'][$childName] = $config;

        return $this;
    }

    /**
     * Add a simple metric aggregation.
     */
    private function addMetricAgg(string $name, string $type, string $field): static
    {
        $this->aggregations[$name] = [$type => ['field' => $field]];

        return $this;
    }

    /**
     * Add a bucket aggregation with sub-aggregation support.
     */
    private function addBucketAgg(string $name, string $type, array $config): static
    {
        $this->aggregations[$name] = array_merge(
            [$type => $config],
            $this->pendingSubAggs[$name] ?? [],
        );
        unset($this->pendingSubAggs[$name]);

        return $this;
    }
}
